name: Pulsar CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: 192.168.100.20:6443
  JAVA_OPTS: "-Xmx512m"

jobs:
  build-and-push:
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 0. CREATE K8S SECRET FILE FROM GITHUB SECRETS
      - name: Create K8s Secret File
        run: |
          echo "${{ secrets.K8S_ENV_SECRET }}" > k8s/01-environment.yaml

      # 1. SETUP BUILD ENVS
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host 

      # 2. BUILD & PUSH FRONTEND
      - name: Build/Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/frontend:latest,${{ env.REGISTRY }}/frontend:${{ github.sha }}

      # 3. BUILD & PUSH BACKENDS
      - name: Build/Push Services
        run: |
          services="auth-service user-service event-service booking-service"
          for svc in $services; do
            echo "Building $svc..."
            docker build -t ${{ env.REGISTRY }}/$svc:latest -t ${{ env.REGISTRY }}/$svc:${{ github.sha }} ./services/$svc
            docker push ${{ env.REGISTRY }}/$svc:latest
            docker push ${{ env.REGISTRY }}/$svc:${{ github.sha }}
          done

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Manifests
        uses: actions/checkout@v4

      # 4. UPDATE KUBERNETES DEPLOYMENTS
      - name: Deploy to K8s
        run: |
          # Apply the Namespace
          kubectl apply -f k8s/00-namespace.yaml
          
          # Apply Configs & Secrets
          kubectl apply -f k8s/01-environment.yaml

          kubectl apply -f k8s/external-mongo.yaml
          
          # update Images
          kubectl apply -f k8s/
          
          # pull the new image
          kubectl rollout restart deployment/frontend -n pulsar
          kubectl rollout restart deployment/auth-service -n pulsar
          kubectl rollout restart deployment/user-service -n pulsar
          kubectl rollout restart deployment/event-service -n pulsar
          kubectl rollout restart deployment/booking-service -n pulsar